cuff1 <- read.table('accurate.stats.gene.1')
cuff2 <- read.table('accurate.stats.gene.2')
print(mean(cuff1[,1]))
print(mean(cuff2[,1]))
print(mean(cuff1[,1])-mean(cuff2[,1]))
print(mean(cuff1[,2]))
print(mean(cuff2[,2]))
print(mean(cuff1[,2])-mean(cuff2[,2]))
print(mean(cuff1[,3]))
print(mean(cuff2[,3]))
print(mean(cuff1[,3])-mean(cuff2[,3]))
